package com.leetcode;

import java.util.Arrays;

/**
 * 389. Find the Difference
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        char[] ss = s.toCharArray(), tt = t.toCharArray();
        Arrays.sort(ss);
        Arrays.sort(tt);
        for (int i = 0; i < Math.min(ss.length, tt.length); ++i) {
            if (ss[i] != tt[i]) {
                return tt.length > ss.length ? tt[i] : ss[i];
            }
        }
        return tt.length > ss.length ? tt[tt.length - 1] : ss[ss.length - 1];
    }
}
